trigger:
- master

pool:
  name: Default

steps:
- checkout: self

- powershell: |
    ./CheckPredefinedVulnerabilities.ps1 -labScanJarPath "LabScan.jar" -projectPath "." -projectKey "F42C4CFB-1198-409C-8D8C-CB6BF490BA20" -severityLevels "High,Critical" -labradorUrl "https://labrador.labradorlabs.ai" -labradorToken "569e12ff03bc4e5f9e51267c6acdeeed"
  displayName: 'Run LabScan SCA Scan and Check for Vulnerabilities'
