trigger:
- master

pool:
  name: Default

steps:
- powershell: |
    Invoke-WebRequest -Uri 'https://www.dropbox.com/scl/fi/4csr3mujm2we7n082hvwv/LabScan.jar?rlkey=fihpl9ef79xmd1e6kstxavlsv&dl=1' -OutFile 'LabScan.jar'
    java -jar LabScan.jar -project . -token [ApiKey] -projectkey [ProjectKey]
  displayName: 'Download and Run LabScan SCA Scan'
