name: LabScan and SecurityPrism CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  labscan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Download LabScan JAR
      run: |
        wget -O LabScan.jar 'https://www.dropbox.com/scl/fi/4csr3mujm2we7n082hvwv/LabScan.jar?rlkey=fihpl9ef79xmd1e6kstxavlsv&dl=1'

    - name: Download CheckPredefinedVulnerabilities Script
      run: |
        wget -O CheckPredefinedVulnerabilities.sh 'https://www.dropbox.com/scl/fi/5qd65i975k9kt41eimh2b/CheckPredefinedVulnerabilities.sh?rlkey=h24mdr45rx8u3woabhezsy9q0&dl=1'
        sed -i 's/\r$//' CheckPredefinedVulnerabilities.sh  # Convert line endings to Unix-style
        chmod +x CheckPredefinedVulnerabilities.sh

    - name: Run LabScan SCA Scan and Check for Vulnerabilities
      env:
        LABSCAN_JAR_PATH: LabScan.jar
        PROJECT_PATH: .
        PROJECT_KEY: F42C4CFB-1198-409C-8D8C-CB6BF490BA20
        SEVERITY_LEVELS: High,Critical
        LABRADOR_URL: https://labrador.labradorlabs.ai
        LABRADOR_TOKEN: 569e12ff03bc4e5f9e51267c6acdeeed
      run: |
        ./CheckPredefinedVulnerabilities.sh "$LABSCAN_JAR_PATH" "$PROJECT_PATH" "$PROJECT_KEY" "$SEVERITY_LEVELS" "$LABRADOR_URL" "$LABRADOR_TOKEN"

  securityprism:
    runs-on: windows-latest
    needs: labscan

    steps:
    - uses: actions/checkout@v3
    - name: Run SecurityPrism Scan
      run: |
        ./SecurityPrism.ps1 'http://54.67.92.221:60102' 'APPG 080062e7e48b4190b26ebeba168e3d52' 'Python Test' 'master' 
      shell: pwsh
